# Generated by Django 3.0.5 on 2021-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocData',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_title', models.CharField(max_length=50)),
                ('doc_image', models.FileField(default='', max_length=200, upload_to='customer/images')),
            ],
        ),
    ]
