# Generated by Django 3.0.5 on 2021-06-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0002_auto_20210622_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fieldview',
        ),
    ]
