# Generated by Django 3.0.5 on 2021-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitalpocket', '0003_delete_fieldview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldview',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=30)),
                ('field_image', models.ImageField(default='', upload_to='stream')),
                ('field_select', models.CharField(max_length=30)),
            ],
        ),
    ]
