# Generated by Django 3.0.5 on 2021-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0006_auto_20210622_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldview',
            name='field_image',
            field=models.ImageField(default='', upload_to='fields/vehicle'),
        ),
    ]
