# Generated by Django 3.0.5 on 2021-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0008_auto_20210623_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFiledView',
            fields=[
                ('sub_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_field_name', models.CharField(max_length=30)),
                ('sub_field_image', models.ImageField(default='', upload_to='fields/images/Vehicle')),
                ('sub_field_select', models.CharField(max_length=30)),
            ],
        ),
    ]
