# Generated by Django 3.0.5 on 2021-06-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0009_subfiledview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubFiledView',
            new_name='SubFieldView',
        ),
    ]
