# Generated by Django 3.0.5 on 2021-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0011_auto_20210623_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfieldview',
            name='category_field',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
