# Generated by Django 3.0.5 on 2021-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0012_subfieldview_category_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('doc_title', models.CharField(max_length=300)),
                ('doc_image', models.FileField(default='', upload_to='fields/images/uploaded')),
            ],
        ),
    ]
