# Generated by Django 3.0.5 on 2021-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0015_auto_20210729_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='doc_image',
            field=models.FileField(default='', upload_to='fields/images/uploaded'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='doc_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
