# Generated by Django 3.0.5 on 2021-07-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0016_auto_20210729_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='doc_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
