# Generated by Django 3.0.5 on 2021-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0019_auto_20210729_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='doc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
