# Generated by Django 3.0.5 on 2021-07-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0020_auto_20210729_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='doc_id',
            new_name='docs_id',
        ),
    ]
