# Generated by Django 3.0.5 on 2021-07-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0022_auto_20210729_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='doc_image',
            field=models.FileField(default='', upload_to='fields/images/uploaded'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='doc_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='docs_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
