# Generated by Django 3.0.5 on 2021-07-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0023_auto_20210729_0152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
