# Generated by Django 3.0.5 on 2021-07-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalpocket', '0025_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
